In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y,x-y,x/y,x**y

(tensor(5.), tensor(1.), tensor(1.5000), tensor(9.))

In [6]:
x = torch.arange(4)

x

tensor([0, 1, 2, 3])

In [7]:
x[3]

tensor(3)

In [8]:
len(x)

4

In [9]:
x.shape

torch.Size([4])

In [11]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [12]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [13]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [18]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [19]:
a = 2

X = torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [20]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [25]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [26]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [28]:
A.sum(axis=[0,1])

tensor(190.)

In [32]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [33]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [34]:
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [35]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [36]:
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [37]:
y = torch.ones(4,dtype = torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [38]:
torch.sum(x * y)

tensor(6.)

In [40]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [41]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [42]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [43]:
torch.abs(u).sum()

tensor(7.)

In [44]:
torch.norm(torch.ones(4,9))

tensor(6.)

# 2.3线性代数
## 一、基本数学对象
| 对象       | 数学定义与表示                | 代码实现（PyTorch）          | 核心属性                          |
|------------|-----------------------------|-----------------------------|-----------------------------------|
| 标量（Scalar） | 单个实数值，记为小写字母（如$x$），$x \in \mathbb{R}$ | `x = torch.tensor(3.0)`     | 零阶张量，无轴，仅含一个元素      |
| 向量（Vector） | 标量组成的列表，记为粗体小写字母（如$\mathbf{x}$），$\mathbf{x} \in \mathbb{R}^n$（$n$为长度） | `x = torch.arange(4)`       | 一阶张量，单轴，形状为$[n]$；默认列向量 |
| 矩阵（Matrix） | 向量组成的二维表格，记为粗体大写字母（如$\mathbf{A}$），$\mathbf{A} \in \mathbb{R}^{m \times n}$（$m$行$n$列） | `A = torch.arange(20).reshape(5,4)` | 二阶张量，双轴（行轴0、列轴1），形状为$[m,n]$ |
| 张量（Tensor） | 任意维度的数组，记为特殊字体大写字母（如$\mathsf{X}$），$k$阶张量有$k$个轴 | `X = torch.arange(24).reshape(2,3,4)` | 高阶张量（轴数$\geq3$），形状为$[d_1,d_2,...,d_k]$ |

### 关键概念区分
- **维度（dimension）**：  
  - 向量/轴的维度：指向量/轴的长度（元素个数）；  
  - 张量的维度：指张量的轴数（如矩阵是2维张量，对应2个轴）。
- **形状（shape）**：张量沿每个轴的长度组成的元组（如3阶张量形状$[2,3,4]$表示轴0长2、轴1长3、轴2长4）。

## 二、核心运算（含数学定义+代码实现）
### 1. 按元素运算
- 适用场景：相同形状的张量，运算作用于对应位置元素；标量与张量运算时，标量与每个元素作用。
- 常用运算：
  - 加减乘除：`x + y`、`x - y`、`x * y`、`x / y`（标量/张量通用）；
  - 指数：`x ** y`；
  - Hadamard积（矩阵按元素乘法）：$\mathbf{A} \odot \mathbf{B}$，代码`A * B`（注意区别于矩阵乘法）。

### 2. 点积（Dot Product）
- 数学定义：$\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^d x_i y_i$（$\mathbf{x},\mathbf{y} \in \mathbb{R}^d$，结果为标量）；
- 代码实现：`torch.dot(x, y)` 或 `torch.sum(x * y)`；
- 用途：加权和、规范化后向量的夹角余弦计算。

### 3. 矩阵-向量积
- 数学定义：$\mathbf{A}\mathbf{x} \in \mathbb{R}^m$（$\mathbf{A} \in \mathbb{R}^{m \times n}$，$\mathbf{x} \in \mathbb{R}^n$），第$i$个元素为$\mathbf{a}_i^\top \mathbf{x}$（$\mathbf{a}_i$是$\mathbf{A}$的第$i$行向量）；
- 代码实现：`torch.mv(A, x)`（约束：$\mathbf{A}$的列数 = $\mathbf{x}$的长度）；
- 用途：线性变换（如神经网络全连接层前向计算）。

### 4. 矩阵-矩阵乘法
- 数学定义：$\mathbf{C} = \mathbf{A}\mathbf{B} \in \mathbb{R}^{n \times m}$（$\mathbf{A} \in \mathbb{R}^{n \times k}$，$\mathbf{B} \in \mathbb{R}^{k \times m}$），元素$c_{ij} = \mathbf{a}_i^\top \mathbf{b}_j$（$\mathbf{a}_i$是$\mathbf{A}$第$i$行，$\mathbf{b}_j$是$\mathbf{B}$第$j$列）；
- 代码实现：`torch.mm(A, B)`（约束：$\mathbf{A}$的列数 = $\mathbf{B}$的行数）；
- 本质：$m$次矩阵-向量积的结果拼接（$\mathbf{B}$每列对应一次矩阵-向量积）。

### 5. 转置（Transpose）
- 数学定义：$\mathbf{A}^\top$（$\mathbf{A} \in \mathbb{R}^{m \times n}$），形状变为$[n \times m]$，元素$a_{ij}^\top = a_{ji}$；
- 代码实现：`A.T`；
- 性质：$(\mathbf{A}^\top)^\top = \mathbf{A}$、$\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$；
- 特殊矩阵：对称矩阵$\mathbf{A} = \mathbf{A}^\top$。

## 三、降维与累积操作
### 1. 求和（sum）与均值（mean）
- 全量降维：`A.sum()`（所有元素求和）、`A.mean()`（所有元素均值，等价于`A.sum() / A.numel()`，`numel()`返回元素总数）；
- 指定轴降维：`A.sum(axis=0)`（沿行轴求和，消去轴0）、`A.mean(axis=1)`（沿列轴求均值，消去轴1）；
- 多轴降维：`A.sum(axis=[0,1])`（沿轴0和轴1同时求和，等价于全量求和）。

### 2. 非降维求和（keepdims=True）
- 作用：保持张量轴数不变，便于后续广播运算（如矩阵与每行求和结果的逐元素除法）；
- 代码示例：`sum_A = A.sum(axis=1, keepdims=True)`（形状仍为$[5,1]$，而非$[5]$），后续可执行`A / sum_A`。

### 3. 累积求和（cumsum）
- 数学定义：沿指定轴计算元素的累积和，不改变张量形状；
- 代码实现：`A.cumsum(axis=0)`（沿行轴累积求和，第$i$行是前$i$行的和）。

## 四、范数（Norm）
范数是向量/矩阵“大小”的度量，满足4个性质：$f(\alpha\mathbf{x})=|\alpha|f(\mathbf{x})$、$f(\mathbf{x}+\mathbf{y}) \leq f(\mathbf{x})+f(\mathbf{y})$、$f(\mathbf{x}) \geq 0$、$f(\mathbf{x})=0 \iff \mathbf{x}=\mathbf{0}$。

| 范数类型       | 数学定义                                  | 代码实现                  | 特点与用途                          |
|----------------|-------------------------------------------|---------------------------|-----------------------------------|
| $L_2$范数      | $\|\|\mathbf{x}\|\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$ | `torch.norm(u)`           | 欧几里得距离，最常用；省略下标时$\|\|\mathbf{x}\|\| = \|\|\mathbf{x}\|\|_2$ |
| $L_1$范数      | $\|\|\mathbf{x}\|\|_1 = \sum_{i=1}^n |x_i|$ | `torch.abs(u).sum()`      | 抗异常值影响，常用于稀疏性约束      |
| Frobenius范数  | $\|\|\mathbf{X}\|\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$ | `torch.norm(matrix)`      | 矩阵的“$L_2$范数”，满足向量范数所有性质 |

## 五、深度学习中的应用场景
1. **数据表示**：标量（单个属性）、向量（样本特征）、矩阵（样本集合）、张量（图像/视频等多维数据）；
2. **模型计算**：矩阵-向量积（全连接层）、矩阵-矩阵乘法（批量样本计算）、Hadamard积（元素级权重调整）；
3. **优化目标**：范数最小化（如$L_2$正则化抑制过拟合、$L_1$正则化诱导稀疏性）、距离度量（预测值与真实值的范数差）。

## 六、核心小结
1. 线性代数对象的泛化关系：标量（0阶）→ 向量（1阶）→ 矩阵（2阶）→ 张量（高阶）；
2. 运算核心约束：矩阵-向量积要求“矩阵列数=向量长度”，矩阵-矩阵乘法要求“前矩阵列数=后矩阵行数”；
3. 降维操作关键：`axis`指定降维方向，`keepdims=True`保留轴数以支持广播；
4. 范数核心用途：度量大小、约束模型参数、构建优化目标。

## 练习关键思路提示
1. 转置性质证明：从元素定义出发，$(\mathbf{A}^\top)^\top$的元素为$(a_{ji})^\top = a_{ij}$，与$\mathbf{A}$一致；
2. 转置和的性质：$(\mathbf{A}+\mathbf{B})^\top$的元素为$a_{ji}+b_{ji}$，等于$\mathbf{A}^\top + \mathbf{B}^\top$的元素；
3. 对称矩阵判断：$(\mathbf{A}+\mathbf{A}^\top)^\top = \mathbf{A}^\top + (\mathbf{A}^\top)^\top = \mathbf{A}^\top + \mathbf{A}$，故必对称；
4. `len(X)`（$X$形状$[2,3,4]$）：返回轴0的长度（2），`len(X)`始终对应轴0的长度；
5. `A/A.sum(axis=1)`报错：`sum(axis=1)`后形状为$[5]$，与$\mathbf{A}$（$[5,4]$）广播不兼容，需用`keepdims=True`；
6. 3阶张量求和形状：轴0求和→$[3,4]$，轴1求和→$[2,4]$，轴2求和→$[2,3]$；
7. 高阶张量范数：`torch.norm`计算所有元素平方和的平方根（等价于将张量展平为向量后的$L_2$范数）。# 线性代数核心知识总结
