In [4]:
import torch
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
X=x.reshape(3,4)
print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [18]:
# torch.zeros((2,3,4))
# torch.ones((2,3,4))
# torch.randn(3,4)
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim = 0),torch.cat((X,Y),dim = 1)
# X == Y
# X.sum()

tensor(66.)

In [21]:
a = torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [26]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [32]:
before = id(Y)
Y=Y+X
id(Y)==before

False

In [34]:
Z = torch.zeros_like(Y)
print('id(Z)',id(Z))
Z[:] = X+Y
print('id(Z):',id(Z))

id(Z) 1645970806800
id(Z): 1645970806800


In [35]:
before = id(X)
X += Y
id(X) == before

True

In [36]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [37]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.1数据操作summary

## 张量的创建与基础属性

- 用torch.arange(n)创建包含连续元素的张量（如torch.arange(12)生成 0-11 的张量）；
- 用.shape查看张量的形状（如 1 维张量形状为torch.Size([12])）；
- 用.numel()查看张量的元素总数（如 12 个元素的张量，结果为 12）。

## 张量的形状重塑

通过.reshape(shape)调整张量维度（如把 1 维 12 元素的张量，重塑为3×4的 2 维张量）

## 张量的创建方式

- 可通过torch.zeros/ones/rand创建全 0、全 1、随机值张量；
- 用torch.tensor()手动传入数据（如torch.tensor([[2,1,4,3], ...])）创建自定义张量。

## 张量的基本运算

加减乘除（+、-、*、/）、幂运算（$ ** ）等，运算后得到同形状的张量。

## 张量的拼接与求和

- 用torch.cat(tensors, dim)按指定维度拼接张量（dim=0为行拼接，dim=1为列拼接）；
- 用.sum()对张量所有元素求和（如示例中张量求和结果为66.）。

## 张量的广播机制

当两个张量形状不完全匹配但符合 “广播规则” 时，会自动扩展形状后执行逐元素运算：

e.g. a(3,1)和b(1,2)相加，自动扩展为(3,2)形状后运算，得到3×2的张量。

## 张量的索引与切片操作

- 索引：通过下标取部分元素（如X[-1]取最后一行，X[1:3]取第 2-3 行）；
- 赋值：支持单个元素修改（X[1,2]=9）、范围元素批量修改（X[0:2,:]=12修改前两行所有元素）。

## 张量的内存与原地操作

- 普通运算（如Y = Y+X）会创建新张量，内存地址（id()）改变；
- 原地操作（如Z[:] = X+Y、X += Y）会直接修改原张量，内存地址保持不变。

## 张量与 NumPy 的转换

用.numpy()将 PyTorch 张量转为 NumPy 数组；用torch.tensor(NumPy数组)将 NumPy 数组转回 PyTorch 张量；两者类型分别为numpy.ndarray和torch.Tensor。


## 单个元素张量的取值

对仅含 1 个元素的张量，可通过：
- .item()提取为 Python 标量；
- float()/int()直接转换为对应 Python 数值类型。